"""db2

Revision ID: ab53ccf862bc
Revises: afdb1e511241
Create Date: 2024-03-26 06:49:11.266548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab53ccf862bc'
down_revision = 'afdb1e511241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        # Remove the 'data' column if it exists
        batch_op.drop_column('data')


    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('data')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data',
        sa.LargeBinary(),
        nullable=False))

    # ### end Alembic commands ###
